export { BuffersTabContent } from './BuffersTab'
export { PassesTabContent } from './PassesTab'
export { ShaderTabContent } from './ShaderTab'
export { StatsTabContent } from './StatsTab'
export { SystemTabContent } from './SystemTab'
