/**
 * Decoherence & Monitoring Scenario Presets
 *
 * Curated TDSE presets for stochastic decoherence (branching visualization)
 * and continuous monitoring transition exploration.
 *
 * @module lib/physics/tdse/decoherencePresets
 */

import type { TdseScenarioPreset } from './presets'

/** Decoherent branching and monitoring presets. */
export const DECOHERENCE_PRESETS: TdseScenarioPreset[] = [
  // ── Decoherent Branching Presets ──
  {
    id: 'doubleWellBranching',
    name: 'Double Well Branching',
    description: 'Particle in double well — watch left/right pointer-state separation',
    overrides: {
      latticeDim: 3,
      gridSize: [64, 64, 64],
      spacing: [0.1, 0.1, 0.1],
      dt: 0.005,
      stepsPerFrame: 4,
      initialCondition: 'gaussianPacket',
      packetCenter: [0, 0, 0],
      packetWidth: 0.5,
      packetAmplitude: 1.0,
      packetMomentum: [0, 0, 0],
      potentialType: 'doubleWell',
      doubleWellLambda: 8.0,
      doubleWellSeparation: 1.0,
      doubleWellAsymmetry: 0.0,
      absorberEnabled: false,
      diagnosticsEnabled: true,
      diagnosticsInterval: 5,
      fieldView: 'density',
      autoScale: true,
      stochasticEnabled: true,
      stochasticGamma: 1.0,
      stochasticSigma: 2.0,
      stochasticNumSites: 4,
      stochasticSeed: 42,
      branchingEnabled: true,
      branchPlanePosition: 0.0,
      branchColorA: [0.0, 1.0, 1.0],
      branchColorB: [1.0, 0.0, 1.0],
    },
  },
  {
    id: 'barrierBranching',
    name: 'Barrier Branching',
    description: 'Wavepacket hits barrier — transmitted/reflected split with decoherence',
    overrides: {
      latticeDim: 3,
      gridSize: [64, 64, 64],
      spacing: [0.1, 0.1, 0.1],
      dt: 0.005,
      stepsPerFrame: 4,
      initialCondition: 'gaussianPacket',
      packetCenter: [-1.5, 0, 0],
      packetWidth: 0.4,
      packetAmplitude: 1.0,
      packetMomentum: [6.0, 0, 0],
      potentialType: 'barrier',
      barrierHeight: 12.0,
      barrierWidth: 0.2,
      barrierCenter: 0.5,
      absorberEnabled: true,
      absorberWidth: 0.2,
      pmlTargetReflection: 1e-6,
      diagnosticsEnabled: true,
      diagnosticsInterval: 5,
      fieldView: 'density',
      autoScale: true,
      stochasticEnabled: true,
      stochasticGamma: 0.5,
      stochasticSigma: 1.5,
      stochasticNumSites: 4,
      stochasticSeed: 42,
      branchingEnabled: true,
      branchPlanePosition: 0.0,
      branchColorA: [0.0, 1.0, 1.0],
      branchColorB: [1.0, 0.0, 1.0],
    },
  },
  {
    id: 'schrodingersCat',
    name: "Schrödinger's Cat",
    description: 'Slow decoherence of macroscopic superposition in deep double well',
    overrides: {
      latticeDim: 3,
      gridSize: [64, 64, 64],
      spacing: [0.1, 0.1, 0.1],
      dt: 0.005,
      stepsPerFrame: 4,
      initialCondition: 'gaussianPacket',
      packetCenter: [0, 0, 0],
      packetWidth: 0.5,
      packetAmplitude: 1.0,
      packetMomentum: [0, 0, 0],
      potentialType: 'doubleWell',
      doubleWellLambda: 8.0,
      doubleWellSeparation: 1.0,
      doubleWellAsymmetry: 0.0,
      absorberEnabled: false,
      diagnosticsEnabled: true,
      diagnosticsInterval: 5,
      fieldView: 'density',
      autoScale: true,
      stochasticEnabled: true,
      stochasticGamma: 0.2,
      stochasticSigma: 2.0,
      stochasticNumSites: 4,
      stochasticSeed: 42,
      branchingEnabled: true,
      branchPlanePosition: 0.0,
      branchColorA: [0.0, 1.0, 1.0],
      branchColorB: [1.0, 0.0, 1.0],
    },
  },
  {
    id: 'rapidCollapse',
    name: 'Rapid Collapse',
    description: 'Fast environment coupling — immediate localization in barrier potential',
    overrides: {
      latticeDim: 3,
      gridSize: [64, 64, 64],
      spacing: [0.1, 0.1, 0.1],
      dt: 0.005,
      stepsPerFrame: 4,
      initialCondition: 'gaussianPacket',
      packetCenter: [-1.5, 0, 0],
      packetWidth: 0.4,
      packetAmplitude: 1.0,
      packetMomentum: [6.0, 0, 0],
      potentialType: 'barrier',
      barrierHeight: 12.0,
      barrierWidth: 0.2,
      barrierCenter: 0.5,
      absorberEnabled: true,
      absorberWidth: 0.2,
      pmlTargetReflection: 1e-6,
      diagnosticsEnabled: true,
      diagnosticsInterval: 5,
      fieldView: 'density',
      autoScale: true,
      stochasticEnabled: true,
      stochasticGamma: 5.0,
      stochasticSigma: 1.0,
      stochasticNumSites: 8,
      stochasticSeed: 42,
      branchingEnabled: true,
      branchPlanePosition: 0.0,
      branchColorA: [0.0, 1.0, 1.0],
      branchColorB: [1.0, 0.0, 1.0],
    },
  },
  // ── Continuous Monitoring Presets ──
  {
    id: 'boxMonitoring',
    name: 'Box Monitoring',
    description: 'Simplest confining potential — cleanest IPR(γ) curve',
    overrides: {
      latticeDim: 3,
      gridSize: [64, 64, 64],
      spacing: [0.1, 0.1, 0.1],
      dt: 0.005,
      stepsPerFrame: 4,
      initialCondition: 'gaussianPacket',
      packetCenter: [0, 0, 0],
      packetWidth: 0.5,
      packetAmplitude: 1.0,
      packetMomentum: [0, 0, 0],
      potentialType: 'finiteWell',
      wellDepth: 100.0,
      wellWidth: 2.5,
      absorberEnabled: false,
      diagnosticsEnabled: true,
      diagnosticsInterval: 3,
      fieldView: 'density',
      autoScale: true,
      stochasticEnabled: true,
      stochasticGamma: 1.0,
      stochasticSigma: 2.0,
      stochasticNumSites: 4,
      stochasticSeed: 42,
      branchingEnabled: false,
    },
  },
  {
    id: 'harmonicMonitoring',
    name: 'Harmonic Monitoring',
    description: 'Monitoring in smooth confining potential',
    overrides: {
      latticeDim: 3,
      gridSize: [64, 64, 64],
      spacing: [0.1, 0.1, 0.1],
      dt: 0.005,
      stepsPerFrame: 4,
      initialCondition: 'gaussianPacket',
      packetCenter: [0, 0, 0],
      packetWidth: 0.5,
      packetAmplitude: 1.0,
      packetMomentum: [0, 0, 0],
      potentialType: 'harmonicTrap',
      harmonicOmega: 3.0,
      absorberEnabled: false,
      diagnosticsEnabled: true,
      diagnosticsInterval: 3,
      fieldView: 'density',
      autoScale: true,
      stochasticEnabled: true,
      stochasticGamma: 1.0,
      stochasticSigma: 2.0,
      stochasticNumSites: 4,
      stochasticSeed: 42,
      branchingEnabled: false,
    },
  },
  {
    id: 'latticeMonitoring',
    name: 'Lattice Monitoring',
    description: 'Interplay of Bloch delocalization and monitoring',
    overrides: {
      latticeDim: 3,
      gridSize: [64, 64, 64],
      spacing: [0.1, 0.1, 0.1],
      dt: 0.005,
      stepsPerFrame: 4,
      initialCondition: 'gaussianPacket',
      packetCenter: [0, 0, 0],
      packetWidth: 0.5,
      packetAmplitude: 1.0,
      packetMomentum: [3.0, 0, 0],
      potentialType: 'periodicLattice',
      latticeDepth: 5.0,
      latticePeriod: 1.0,
      absorberEnabled: false,
      diagnosticsEnabled: true,
      diagnosticsInterval: 3,
      fieldView: 'density',
      autoScale: true,
      stochasticEnabled: true,
      stochasticGamma: 1.0,
      stochasticSigma: 2.0,
      stochasticNumSites: 4,
      stochasticSeed: 42,
      branchingEnabled: false,
    },
  },
  {
    id: 'chaoticMonitoring',
    name: 'Chaotic Monitoring',
    description: 'How does chaos affect the IPR(γ) curve?',
    overrides: {
      latticeDim: 3,
      gridSize: [64, 64, 64],
      spacing: [0.1, 0.1, 0.1],
      dt: 0.005,
      stepsPerFrame: 4,
      initialCondition: 'gaussianPacket',
      packetCenter: [0, 0, 0],
      packetWidth: 0.5,
      packetAmplitude: 1.0,
      packetMomentum: [3.0, 0, 0],
      potentialType: 'coupledAnharmonic',
      anharmonicLambda: 2.0,
      harmonicOmega: 1.0,
      absorberEnabled: false,
      diagnosticsEnabled: true,
      diagnosticsInterval: 3,
      fieldView: 'density',
      autoScale: true,
      stochasticEnabled: true,
      stochasticGamma: 1.0,
      stochasticSigma: 2.0,
      stochasticNumSites: 4,
      stochasticSeed: 42,
      branchingEnabled: false,
    },
  },
]
