/**
 * Curated Wheeler–DeWitt minisuperspace scenario presets.
 *
 * Each preset overrides a scoped scenario subset on `WheelerDeWittConfig`.
 * 3D presets leave grid parameters untouched; 4D presets set conservative
 * grid defaults and disable unsupported overlays.
 *
 * @module lib/physics/wheelerDeWitt/presets
 */

import type { WheelerDeWittConfig } from '@/lib/geometry/extended/wheelerDeWitt'
import type { ScenarioPreset } from '@/lib/physics/presetTypes'

/** A curated Wheeler–DeWitt scenario with physics-field overrides. */
export type WdwScenarioPreset = ScenarioPreset<Partial<WheelerDeWittConfig>>

/**
 * Physics-field subset that a Wheeler–DeWitt preset is allowed to override.
 * Enforced at the apply-action site so grid and render-only fields stay
 * outside the preset contract.
 *
 * `inflatonMassAsymmetry` is included so preset apply always resets to
 * the preset's intended isotropy state. Previously it was omitted, and
 * stale asymmetry from a prior interactive edit survived preset switches
 * silently — altering SRMT diagnostics and the solve without any UI cue.
 */
export const WDW_PRESET_PHYSICS_FIELDS = [
  'minisuperspaceDimension',
  'boundaryCondition',
  'inflatonMass',
  'inflatonMassAsymmetry',
  'cosmologicalConstant',
  'gridNa',
  'gridNphi',
  'phi3SliceNormalized',
  'streamlinesEnabled',
  'worldlineEnabled',
  'srmtEnabled',
] as const

// Every preset is explicitly isotropic (`inflatonMassAsymmetry: 1`) so
// applying a preset clears any stale anisotropy from prior interactive
// edits. The anisotropic case is an SRMT-discriminator experiment, not
// part of the curated scenarios.
export const WDW_SCENARIO_PRESETS: WdwScenarioPreset[] = [
  {
    id: 'noBoundaryBaseline',
    name: 'Hartle–Hawking Baseline',
    description:
      'No-boundary proposal with Λ = 0 — real, exponentially damped wave function on flat minisuperspace',
    overrides: {
      minisuperspaceDimension: 3,
      boundaryCondition: 'noBoundary',
      inflatonMass: 0.3,
      inflatonMassAsymmetry: 1,
      cosmologicalConstant: 0.0,
    },
  },
  {
    id: 'vilenkinTunneling',
    name: 'Vilenkin Tunneling',
    description:
      'Tunneling proposal with small positive Λ — complex oscillating initial data favouring expansion',
    overrides: {
      minisuperspaceDimension: 3,
      boundaryCondition: 'tunneling',
      inflatonMass: 0.3,
      inflatonMassAsymmetry: 1,
      cosmologicalConstant: 0.3,
    },
  },
  {
    id: 'deWittOrigin',
    name: 'DeWitt χ(0,·) = 0',
    description:
      "DeWitt node at the origin with the solver's Gaussian derivative seed — wave function vanishes at the classical singularity",
    overrides: {
      minisuperspaceDimension: 3,
      boundaryCondition: 'deWitt',
      inflatonMass: 0.3,
      inflatonMassAsymmetry: 1,
      cosmologicalConstant: 0.0,
    },
  },
  {
    id: 'inflationHighMass',
    name: 'Heavy Inflaton',
    description:
      'No-boundary run with m = 0.8 — stiffer quadratic potential, richer quantum-potential structure',
    overrides: {
      minisuperspaceDimension: 3,
      boundaryCondition: 'noBoundary',
      inflatonMass: 0.8,
      inflatonMassAsymmetry: 1,
      cosmologicalConstant: 0.0,
    },
  },
  {
    id: 'deSitterLargeLambda',
    name: 'de Sitter Λ = 0.8',
    description:
      'Large positive cosmological constant — classical turning point near the nucleation radius. Note: Λ ≥ 0.85-like regimes sit above the Airy/Langer Stage-3 ceiling (|ζ_max| < 1.15), so the Euclidean tail is generated by the Stage-2 absorber + match-cell propagator and is BC-agnostic — swapping the BC selector between Hartle-Hawking and Vilenkin will not visibly change the Euclidean region for this preset.',
    overrides: {
      minisuperspaceDimension: 3,
      boundaryCondition: 'noBoundary',
      inflatonMass: 0.3,
      inflatonMassAsymmetry: 1,
      cosmologicalConstant: 0.8,
    },
  },
  {
    id: 'antiDeSitterContracting',
    name: 'Anti-de Sitter Λ = −0.5',
    description:
      'Negative Λ with no-boundary (Hartle–Hawking) BC — real-valued χ = equal superposition of expanding and contracting classical branches (the AdS-oscillatory signature), plus visibly oscillatory bulk density. Previously shipped with Vilenkin/tunneling BC, which has no principled definition for Λ < 0 (Vilenkin selects the outgoing branch relative to a classical turning surface; none exists inside the grid for Λ < 0, m = 0.3, so the boundary-seeded Gaussian just leaked into the Euclidean corners and produced a Bi-runaway that crushed the Lorentzian bulk into invisibility). Raising `m` from 0.3 → 0.5 moves the classical turning surface `|φ|² = 2|Λ|/m²` inward from 3.33 to 2.0, so the grid hosts a genuine Lorentzian / Euclidean split and WKB streamlines pick up φ-motion instead of collapsing into seed dots along the a-axis.',
    overrides: {
      minisuperspaceDimension: 3,
      boundaryCondition: 'noBoundary',
      inflatonMass: 0.5,
      inflatonMassAsymmetry: 1,
      cosmologicalConstant: -0.5,
    },
  },
  {
    id: 'fourDimensionalNoBoundarySlice',
    name: '4D Hartle–Hawking Slice',
    description:
      '4D no-boundary minisuperspace with a fixed φ₃ mid-slice, conservative 48×12³ grid, and no SRMT or WKB streamlines',
    overrides: {
      minisuperspaceDimension: 4,
      boundaryCondition: 'noBoundary',
      inflatonMass: 0.25,
      inflatonMassAsymmetry: 1,
      cosmologicalConstant: 0.15,
      gridNa: 48,
      gridNphi: 12,
      phi3SliceNormalized: 0.5,
      streamlinesEnabled: false,
      worldlineEnabled: false,
      srmtEnabled: false,
    },
  },
  {
    id: 'fourDimensionalTunnelingRidge',
    name: '4D Tunneling Ridge',
    description:
      '4D Vilenkin tunneling scenario rendered at an off-centre φ₃ slice to expose slice-dependent density structure',
    overrides: {
      minisuperspaceDimension: 4,
      boundaryCondition: 'tunneling',
      inflatonMass: 0.35,
      inflatonMassAsymmetry: 1,
      cosmologicalConstant: 0.25,
      gridNa: 48,
      gridNphi: 12,
      phi3SliceNormalized: 0.65,
      streamlinesEnabled: false,
      worldlineEnabled: false,
      srmtEnabled: false,
    },
  },
]

/** Dimension owned by a WDW scenario preset. */
export function getWdwPresetDimension(preset: WdwScenarioPreset): 3 | 4 {
  return preset.overrides.minisuperspaceDimension ?? 3
}

/** Filter WDW scenarios by the active global dimension selector. */
export function getWdwPresetsForGeometryDimension(dimension: number): WdwScenarioPreset[] {
  const target = dimension === 4 ? 4 : 3
  return WDW_SCENARIO_PRESETS.filter((preset) => getWdwPresetDimension(preset) === target)
}

/** Lookup a Wheeler–DeWitt preset by id. */
export function getWdwPreset(id: string): WdwScenarioPreset | undefined {
  return WDW_SCENARIO_PRESETS.find((p) => p.id === id)
}
