/**
 * Hook that wires the extended object store into typed action objects
 * for each quantum mode's child controls component.
 */

import { useShallow } from 'zustand/react/shallow'
import { useExtendedObjectStore, type ExtendedObjectState } from '@/stores/extendedObjectStore'
import type {
  BecActions,
  DiracActions,
  FreeScalarFieldActions,
  HarmonicOscillatorActions,
  HydrogenNDActions,
  TdseActions,
  WignerActions,
} from './types'
import type { SchroedingerConfig } from '@/lib/geometry/extended/types'

/** Return type of the useSchroedingerActions hook. */
export interface SchroedingerActionsResult {
  config: SchroedingerConfig
  setRepresentation: ExtendedObjectState['setSchroedingerRepresentation']
  setMomentumDisplayUnits: ExtendedObjectState['setSchroedingerMomentumDisplayUnits']
  setMomentumScale: ExtendedObjectState['setSchroedingerMomentumScale']
  setMomentumHbar: ExtendedObjectState['setSchroedingerMomentumHbar']
  harmonicActions: HarmonicOscillatorActions
  hydrogenNDActions: HydrogenNDActions
  wignerActions: WignerActions
  freeScalarActions: FreeScalarFieldActions
  tdseActions: TdseActions
  becActions: BecActions
  diracActions: DiracActions
}

/**
 * Subscribes to the extended object store and returns typed action bundles
 * for each quantum physics mode.
 */
export function useSchroedingerActions(): SchroedingerActionsResult {
  const extendedObjectSelector = useShallow((state: ExtendedObjectState) => ({
    config: state.schroedinger,
    setRepresentation: state.setSchroedingerRepresentation,
    setMomentumDisplayUnits: state.setSchroedingerMomentumDisplayUnits,
    setMomentumScale: state.setSchroedingerMomentumScale,
    setMomentumHbar: state.setSchroedingerMomentumHbar,
    // Harmonic oscillator actions
    setPresetName: state.setSchroedingerPresetName,
    setSeed: state.setSchroedingerSeed,
    randomizeSeed: state.randomizeSchroedingerSeed,
    setTermCount: state.setSchroedingerTermCount,
    setMaxQuantumNumber: state.setSchroedingerMaxQuantumNumber,
    setFrequencySpread: state.setSchroedingerFrequencySpread,
    setFieldScale: state.setSchroedingerFieldScale,
    setSchroedingerParameterValue: state.setSchroedingerParameterValue,
    resetSchroedingerParameters: state.resetSchroedingerParameters,
    // Hydrogen actions
    setPrincipalQuantumNumber: state.setSchroedingerPrincipalQuantumNumber,
    setAzimuthalQuantumNumber: state.setSchroedingerAzimuthalQuantumNumber,
    setMagneticQuantumNumber: state.setSchroedingerMagneticQuantumNumber,
    setUseRealOrbitals: state.setSchroedingerUseRealOrbitals,
    setBohrRadiusScale: state.setSchroedingerBohrRadiusScale,
    // Hydrogen ND actions
    setHydrogenNDPreset: state.setSchroedingerHydrogenNDPreset,
    setExtraDimQuantumNumber: state.setSchroedingerExtraDimQuantumNumber,
    setExtraDimFrequencySpread: state.setSchroedingerExtraDimFrequencySpread,
    // Wigner actions
    setWignerDimensionIndex: state.setSchroedingerWignerDimensionIndex,
    setWignerAutoRange: state.setSchroedingerWignerAutoRange,
    setWignerXRange: state.setSchroedingerWignerXRange,
    setWignerPRange: state.setSchroedingerWignerPRange,
    setWignerCrossTermsEnabled: state.setSchroedingerWignerCrossTermsEnabled,
    setWignerQuadPoints: state.setSchroedingerWignerQuadPoints,
    setWignerClassicalOverlay: state.setSchroedingerWignerClassicalOverlay,
    setWignerCacheResolution: state.setSchroedingerWignerCacheResolution,
    // Free scalar field actions
    setFreeScalarLatticeDim: state.setFreeScalarLatticeDim,
    setFreeScalarGridSize: state.setFreeScalarGridSize,
    setFreeScalarSpacing: state.setFreeScalarSpacing,
    setFreeScalarMass: state.setFreeScalarMass,
    setFreeScalarDt: state.setFreeScalarDt,
    setFreeScalarStepsPerFrame: state.setFreeScalarStepsPerFrame,
    setFreeScalarInitialCondition: state.setFreeScalarInitialCondition,
    setFreeScalarFieldView: state.setFreeScalarFieldView,
    setFreeScalarPacketCenter: state.setFreeScalarPacketCenter,
    setFreeScalarPacketWidth: state.setFreeScalarPacketWidth,
    setFreeScalarPacketAmplitude: state.setFreeScalarPacketAmplitude,
    setFreeScalarModeK: state.setFreeScalarModeK,
    setFreeScalarAutoScale: state.setFreeScalarAutoScale,
    setFreeScalarVacuumSeed: state.setFreeScalarVacuumSeed,
    setFreeScalarSlicePosition: state.setFreeScalarSlicePosition,
    resetFreeScalarField: state.resetFreeScalarField,
    setFreeScalarSelfInteractionEnabled: state.setFreeScalarSelfInteractionEnabled,
    setFreeScalarSelfInteractionLambda: state.setFreeScalarSelfInteractionLambda,
    setFreeScalarSelfInteractionVev: state.setFreeScalarSelfInteractionVev,
    // TDSE dynamics actions
    setTdseLatticeDim: state.setTdseLatticeDim,
    setTdseGridSize: state.setTdseGridSize,
    setTdseSpacing: state.setTdseSpacing,
    setTdseMass: state.setTdseMass,
    setTdseHbar: state.setTdseHbar,
    setTdseDt: state.setTdseDt,
    setTdseStepsPerFrame: state.setTdseStepsPerFrame,
    setTdseInitialCondition: state.setTdseInitialCondition,
    setTdsePacketCenter: state.setTdsePacketCenter,
    setTdsePacketWidth: state.setTdsePacketWidth,
    setTdsePacketAmplitude: state.setTdsePacketAmplitude,
    setTdsePacketMomentum: state.setTdsePacketMomentum,
    setTdsePotentialType: state.setTdsePotentialType,
    setTdseBarrierHeight: state.setTdseBarrierHeight,
    setTdseBarrierWidth: state.setTdseBarrierWidth,
    setTdseBarrierCenter: state.setTdseBarrierCenter,
    setTdseWellDepth: state.setTdseWellDepth,
    setTdseWellWidth: state.setTdseWellWidth,
    setTdseHarmonicOmega: state.setTdseHarmonicOmega,
    setTdseStepHeight: state.setTdseStepHeight,
    setTdseSlitSeparation: state.setTdseSlitSeparation,
    setTdseSlitWidth: state.setTdseSlitWidth,
    setTdseWallThickness: state.setTdseWallThickness,
    setTdseWallHeight: state.setTdseWallHeight,
    setTdseLatticeDepth: state.setTdseLatticeDepth,
    setTdseLatticePeriod: state.setTdseLatticePeriod,
    setTdseDoubleWellLambda: state.setTdseDoubleWellLambda,
    setTdseDoubleWellSeparation: state.setTdseDoubleWellSeparation,
    setTdseDoubleWellAsymmetry: state.setTdseDoubleWellAsymmetry,
    setTdseRadialWellInner: state.setTdseRadialWellInner,
    setTdseRadialWellOuter: state.setTdseRadialWellOuter,
    setTdseRadialWellDepth: state.setTdseRadialWellDepth,
    setTdseRadialWellTilt: state.setTdseRadialWellTilt,
    setTdseDriveEnabled: state.setTdseDriveEnabled,
    setTdseDriveWaveform: state.setTdseDriveWaveform,
    setTdseDriveFrequency: state.setTdseDriveFrequency,
    setTdseDriveAmplitude: state.setTdseDriveAmplitude,
    setTdseAbsorberEnabled: state.setTdseAbsorberEnabled,
    setTdseAbsorberWidth: state.setTdseAbsorberWidth,
    setTdseAbsorberStrength: state.setTdseAbsorberStrength,
    setTdseFieldView: state.setTdseFieldView,
    setTdseAutoScale: state.setTdseAutoScale,
    setTdseShowPotential: state.setTdseShowPotential,
    setTdseDiagnosticsEnabled: state.setTdseDiagnosticsEnabled,
    setTdseDiagnosticsInterval: state.setTdseDiagnosticsInterval,
    setTdseSlicePosition: state.setTdseSlicePosition,
    applyTdsePreset: state.applyTdsePreset,
    resetTdseField: state.resetTdseField,
    // BEC dynamics actions
    setBecInteractionStrength: state.setBecInteractionStrength,
    setBecTrapOmega: state.setBecTrapOmega,
    setBecTrapAnisotropy: state.setBecTrapAnisotropy,
    setBecInitialCondition: state.setBecInitialCondition,
    setBecFieldView: state.setBecFieldView,
    setBecVortexCharge: state.setBecVortexCharge,
    setBecVortexLatticeCount: state.setBecVortexLatticeCount,
    setBecSolitonDepth: state.setBecSolitonDepth,
    setBecSolitonVelocity: state.setBecSolitonVelocity,
    setBecAutoScale: state.setBecAutoScale,
    setBecAbsorberEnabled: state.setBecAbsorberEnabled,
    setBecAbsorberWidth: state.setBecAbsorberWidth,
    setBecAbsorberStrength: state.setBecAbsorberStrength,
    setBecDiagnosticsEnabled: state.setBecDiagnosticsEnabled,
    setBecDiagnosticsInterval: state.setBecDiagnosticsInterval,
    setBecDt: state.setBecDt,
    setBecStepsPerFrame: state.setBecStepsPerFrame,
    setBecMass: state.setBecMass,
    setBecHbar: state.setBecHbar,
    setBecGridSize: state.setBecGridSize,
    setBecSpacing: state.setBecSpacing,
    setBecSlicePosition: state.setBecSlicePosition,
    applyBecPreset: state.applyBecPreset,
    resetBecField: state.resetBecField,
    // Dirac equation actions
    setDiracInitialCondition: state.setDiracInitialCondition,
    setDiracFieldView: state.setDiracFieldView,
    setDiracPotentialType: state.setDiracPotentialType,
    setDiracPotentialStrength: state.setDiracPotentialStrength,
    setDiracPotentialWidth: state.setDiracPotentialWidth,
    setDiracPotentialCenter: state.setDiracPotentialCenter,
    setDiracHarmonicOmega: state.setDiracHarmonicOmega,
    setDiracCoulombZ: state.setDiracCoulombZ,
    setDiracMass: state.setDiracMass,
    setDiracSpeedOfLight: state.setDiracSpeedOfLight,
    setDiracHbar: state.setDiracHbar,
    setDiracDt: state.setDiracDt,
    setDiracStepsPerFrame: state.setDiracStepsPerFrame,
    setDiracGridSize: state.setDiracGridSize,
    setDiracSpacing: state.setDiracSpacing,
    setDiracPacketCenter: state.setDiracPacketCenter,
    setDiracPacketWidth: state.setDiracPacketWidth,
    setDiracPacketMomentum: state.setDiracPacketMomentum,
    setDiracPositiveEnergyFraction: state.setDiracPositiveEnergyFraction,
    setDiracAutoScale: state.setDiracAutoScale,
    setDiracShowPotential: state.setDiracShowPotential,
    setDiracAbsorberEnabled: state.setDiracAbsorberEnabled,
    setDiracAbsorberWidth: state.setDiracAbsorberWidth,
    setDiracAbsorberStrength: state.setDiracAbsorberStrength,
    setDiracDiagnosticsEnabled: state.setDiracDiagnosticsEnabled,
    setDiracDiagnosticsInterval: state.setDiracDiagnosticsInterval,
    setDiracSlicePosition: state.setDiracSlicePosition,
    setDiracNeedsReset: state.setDiracNeedsReset,
    applyDiracPreset: state.applyDiracPreset,
  }))

  const s = useExtendedObjectStore(extendedObjectSelector)

  const harmonicActions: HarmonicOscillatorActions = {
    setPresetName: s.setPresetName,
    setSeed: s.setSeed,
    randomizeSeed: s.randomizeSeed,
    setTermCount: s.setTermCount,
    setMaxQuantumNumber: s.setMaxQuantumNumber,
    setFrequencySpread: s.setFrequencySpread,
    setFieldScale: s.setFieldScale,
    setSchroedingerParameterValue: s.setSchroedingerParameterValue,
    resetSchroedingerParameters: s.resetSchroedingerParameters,
  }

  const hydrogenNDActions: HydrogenNDActions = {
    setPrincipalQuantumNumber: s.setPrincipalQuantumNumber,
    setAzimuthalQuantumNumber: s.setAzimuthalQuantumNumber,
    setMagneticQuantumNumber: s.setMagneticQuantumNumber,
    setUseRealOrbitals: s.setUseRealOrbitals,
    setBohrRadiusScale: s.setBohrRadiusScale,
    setHydrogenNDPreset: s.setHydrogenNDPreset,
    setExtraDimQuantumNumber: s.setExtraDimQuantumNumber,
    setExtraDimFrequencySpread: s.setExtraDimFrequencySpread,
  }

  const wignerActions: WignerActions = {
    setDimensionIndex: s.setWignerDimensionIndex,
    setAutoRange: s.setWignerAutoRange,
    setXRange: s.setWignerXRange,
    setPRange: s.setWignerPRange,
    setCrossTermsEnabled: s.setWignerCrossTermsEnabled,
    setQuadPoints: s.setWignerQuadPoints,
    setClassicalOverlay: s.setWignerClassicalOverlay,
    setCacheResolution: s.setWignerCacheResolution,
  }

  const freeScalarActions: FreeScalarFieldActions = {
    setLatticeDim: s.setFreeScalarLatticeDim,
    setGridSize: s.setFreeScalarGridSize,
    setSpacing: s.setFreeScalarSpacing,
    setMass: s.setFreeScalarMass,
    setDt: s.setFreeScalarDt,
    setStepsPerFrame: s.setFreeScalarStepsPerFrame,
    setInitialCondition: s.setFreeScalarInitialCondition,
    setFieldView: s.setFreeScalarFieldView,
    setPacketCenter: s.setFreeScalarPacketCenter,
    setPacketWidth: s.setFreeScalarPacketWidth,
    setPacketAmplitude: s.setFreeScalarPacketAmplitude,
    setModeK: s.setFreeScalarModeK,
    setAutoScale: s.setFreeScalarAutoScale,
    setVacuumSeed: s.setFreeScalarVacuumSeed,
    setSlicePosition: s.setFreeScalarSlicePosition,
    resetField: s.resetFreeScalarField,
    setSelfInteractionEnabled: s.setFreeScalarSelfInteractionEnabled,
    setSelfInteractionLambda: s.setFreeScalarSelfInteractionLambda,
    setSelfInteractionVev: s.setFreeScalarSelfInteractionVev,
  }

  const tdseActions: TdseActions = {
    setLatticeDim: s.setTdseLatticeDim,
    setGridSize: s.setTdseGridSize,
    setSpacing: s.setTdseSpacing,
    setMass: s.setTdseMass,
    setHbar: s.setTdseHbar,
    setDt: s.setTdseDt,
    setStepsPerFrame: s.setTdseStepsPerFrame,
    setInitialCondition: s.setTdseInitialCondition,
    setPacketCenter: s.setTdsePacketCenter,
    setPacketWidth: s.setTdsePacketWidth,
    setPacketAmplitude: s.setTdsePacketAmplitude,
    setPacketMomentum: s.setTdsePacketMomentum,
    setPotentialType: s.setTdsePotentialType,
    setBarrierHeight: s.setTdseBarrierHeight,
    setBarrierWidth: s.setTdseBarrierWidth,
    setBarrierCenter: s.setTdseBarrierCenter,
    setWellDepth: s.setTdseWellDepth,
    setWellWidth: s.setTdseWellWidth,
    setHarmonicOmega: s.setTdseHarmonicOmega,
    setStepHeight: s.setTdseStepHeight,
    setSlitSeparation: s.setTdseSlitSeparation,
    setSlitWidth: s.setTdseSlitWidth,
    setWallThickness: s.setTdseWallThickness,
    setWallHeight: s.setTdseWallHeight,
    setLatticeDepth: s.setTdseLatticeDepth,
    setLatticePeriod: s.setTdseLatticePeriod,
    setDoubleWellLambda: s.setTdseDoubleWellLambda,
    setDoubleWellSeparation: s.setTdseDoubleWellSeparation,
    setDoubleWellAsymmetry: s.setTdseDoubleWellAsymmetry,
    setRadialWellInner: s.setTdseRadialWellInner,
    setRadialWellOuter: s.setTdseRadialWellOuter,
    setRadialWellDepth: s.setTdseRadialWellDepth,
    setRadialWellTilt: s.setTdseRadialWellTilt,
    setDriveEnabled: s.setTdseDriveEnabled,
    setDriveWaveform: s.setTdseDriveWaveform,
    setDriveFrequency: s.setTdseDriveFrequency,
    setDriveAmplitude: s.setTdseDriveAmplitude,
    setAbsorberEnabled: s.setTdseAbsorberEnabled,
    setAbsorberWidth: s.setTdseAbsorberWidth,
    setAbsorberStrength: s.setTdseAbsorberStrength,
    setFieldView: s.setTdseFieldView,
    setAutoScale: s.setTdseAutoScale,
    setShowPotential: s.setTdseShowPotential,
    setDiagnosticsEnabled: s.setTdseDiagnosticsEnabled,
    setDiagnosticsInterval: s.setTdseDiagnosticsInterval,
    setSlicePosition: s.setTdseSlicePosition,
    applyPreset: s.applyTdsePreset,
    resetField: s.resetTdseField,
  }

  const becActions: BecActions = {
    setInteractionStrength: s.setBecInteractionStrength,
    setTrapOmega: s.setBecTrapOmega,
    setTrapAnisotropy: s.setBecTrapAnisotropy,
    setInitialCondition: s.setBecInitialCondition,
    setFieldView: s.setBecFieldView,
    setVortexCharge: s.setBecVortexCharge,
    setVortexLatticeCount: s.setBecVortexLatticeCount,
    setSolitonDepth: s.setBecSolitonDepth,
    setSolitonVelocity: s.setBecSolitonVelocity,
    setAutoScale: s.setBecAutoScale,
    setAbsorberEnabled: s.setBecAbsorberEnabled,
    setAbsorberWidth: s.setBecAbsorberWidth,
    setAbsorberStrength: s.setBecAbsorberStrength,
    setDiagnosticsEnabled: s.setBecDiagnosticsEnabled,
    setDiagnosticsInterval: s.setBecDiagnosticsInterval,
    setDt: s.setBecDt,
    setStepsPerFrame: s.setBecStepsPerFrame,
    setMass: s.setBecMass,
    setHbar: s.setBecHbar,
    setGridSize: s.setBecGridSize,
    setSpacing: s.setBecSpacing,
    setSlicePosition: s.setBecSlicePosition,
    applyPreset: s.applyBecPreset,
    resetField: s.resetBecField,
  }

  const diracActions: DiracActions = {
    setInitialCondition: s.setDiracInitialCondition,
    setFieldView: s.setDiracFieldView,
    setPotentialType: s.setDiracPotentialType,
    setPotentialStrength: s.setDiracPotentialStrength,
    setPotentialWidth: s.setDiracPotentialWidth,
    setPotentialCenter: s.setDiracPotentialCenter,
    setHarmonicOmega: s.setDiracHarmonicOmega,
    setCoulombZ: s.setDiracCoulombZ,
    setMass: s.setDiracMass,
    setSpeedOfLight: s.setDiracSpeedOfLight,
    setHbar: s.setDiracHbar,
    setDt: s.setDiracDt,
    setStepsPerFrame: s.setDiracStepsPerFrame,
    setGridSize: s.setDiracGridSize,
    setSpacing: s.setDiracSpacing,
    setPacketCenter: s.setDiracPacketCenter,
    setPacketWidth: s.setDiracPacketWidth,
    setPacketMomentum: s.setDiracPacketMomentum,
    setPositiveEnergyFraction: s.setDiracPositiveEnergyFraction,
    setAutoScale: s.setDiracAutoScale,
    setShowPotential: s.setDiracShowPotential,
    setAbsorberEnabled: s.setDiracAbsorberEnabled,
    setAbsorberWidth: s.setDiracAbsorberWidth,
    setAbsorberStrength: s.setDiracAbsorberStrength,
    setDiagnosticsEnabled: s.setDiracDiagnosticsEnabled,
    setDiagnosticsInterval: s.setDiracDiagnosticsInterval,
    setSlicePosition: s.setDiracSlicePosition,
    setNeedsReset: s.setDiracNeedsReset,
    applyPreset: s.applyDiracPreset,
  }

  return {
    config: s.config,
    setRepresentation: s.setRepresentation,
    setMomentumDisplayUnits: s.setMomentumDisplayUnits,
    setMomentumScale: s.setMomentumScale,
    setMomentumHbar: s.setMomentumHbar,
    harmonicActions,
    hydrogenNDActions,
    wignerActions,
    freeScalarActions,
    tdseActions,
    becActions,
    diracActions,
  }
}
