/**
 * Compile-time sparse gamma tables for Dirac kernels.
 *
 * The α-matrices and β generated by the Pauli-tensor-product + standard-form
 * permutation are *monomial*: each row has exactly ONE non-zero complex entry.
 * (Proof: σ1, σ2, σ3, I are 2×2 monomial; Kronecker products preserve the
 * per-row-nonzero count multiplicatively; permutation conjugation P·M·P^T
 * preserves the per-row-nonzero count when M is monomial.)
 *
 * Dense S×S·matCount matrix-vector multiplies therefore do S−1 redundant
 * 0·x ops per row. This module runs the CPU-side gamma generator and emits
 * WGSL const arrays holding the single (col, re, im) entry per row per matrix
 * so the kinetic and write-grid kernels can replace their col loop with a
 * single lookup.
 *
 * IEEE bit-identity with the dense path is guaranteed: the dense loop sums
 * gRe·psiR − gIm·psiI over S cols where S−1 contribute exactly 0.0; adding
 * signed-finite 0 to any finite value is bit-preserving in IEEE-754.
 *
 * Specialization scope matches the task spec: latticeDim ∈ {1, 2, 3, 4}
 * (S ∈ {2, 4}, the common modes). Higher dims fall through to the dense loop.
 *
 * @module
 */

import { generateDiracMatricesFallback } from '@/lib/physics/dirac/cliffordAlgebraFallback'

/** Highest latticeDim for which sparse specialization is emitted. */
export const DIRAC_SPARSE_MAX_DIM = 4

/** Single non-zero cell of a monomial row. */
export interface SparseCell {
  readonly col: number
  readonly re: number
  readonly im: number
}

/** Sparse monomial representation of a single S×S complex matrix. */
export interface SparseMatrix {
  /** Length = S. rows[r] = the one non-zero cell on row r. */
  readonly rows: readonly SparseCell[]
}

/**
 * Extract monomial rows from a dense complex-interleaved S×S matrix.
 * Verifies exactly one non-zero per row; throws otherwise — the Clifford
 * generator is deterministic so a violation means a code regression.
 *
 * @param dense - Float32Array of length S*S*2, re/im interleaved row-major.
 * @param s - Spinor size S.
 * @returns Sparse monomial representation.
 */
function extractMonomial(dense: Float32Array, s: number): SparseMatrix {
  const rows: SparseCell[] = []
  for (let r = 0; r < s; r++) {
    let foundCol = -1
    let foundRe = 0
    let foundIm = 0
    for (let c = 0; c < s; c++) {
      const re = dense[(r * s + c) * 2]!
      const im = dense[(r * s + c) * 2 + 1]!
      if (re !== 0 || im !== 0) {
        if (foundCol !== -1) {
          throw new Error(
            `Dirac gamma matrix is not monomial at row ${r}: ` +
              `nonzero at cols ${foundCol} and ${c} — sparsity invariant broken`
          )
        }
        foundCol = c
        foundRe = re
        foundIm = im
      }
    }
    if (foundCol === -1) {
      throw new Error(`Dirac gamma matrix has zero row ${r} — unexpected`)
    }
    rows.push({ col: foundCol, re: foundRe, im: foundIm })
  }
  return { rows }
}

/**
 * Run the Clifford generator and extract sparse monomial tables for every
 * α and β matrix at the given lattice dimension.
 *
 * @param latticeDim - Spatial lattice dimension.
 * @returns Matrices in the order the GPU buffer holds them: α_0..α_{D−1}, β.
 */
export function buildDiracSparseTables(latticeDim: number): readonly SparseMatrix[] {
  const { gammaData, spinorSize: s } = generateDiracMatricesFallback(latticeDim)
  const matSize = s * s * 2
  const out: SparseMatrix[] = []
  // Skip 1-float header (packed spinor size)
  for (let m = 0; m < latticeDim + 1; m++) {
    const offset = 1 + m * matSize
    const slice = gammaData.subarray(offset, offset + matSize)
    out.push(extractMonomial(slice, s))
  }
  return out
}

/**
 * Format a float as a WGSL literal. WGSL does not allow bare int literals
 * where f32 is expected; append `.0` when the mantissa is integer.
 */
function wgslF32(x: number): string {
  if (!Number.isFinite(x)) {
    // Shouldn't happen for Clifford outputs.
    throw new Error(`Non-finite gamma entry: ${x}`)
  }
  const s = x.toString()
  return s.includes('.') || s.includes('e') || s.includes('E') ? s : `${s}.0`
}

/**
 * Emit a WGSL const declaration of the full sparse table for one shader
 * compilation (latticeDim). Produces three flat arrays indexed as
 * `matIdx * S + row`:
 *
 *   const DIRAC_SPARSE_COL: array<u32, COUNT> = array(...)
 *   const DIRAC_SPARSE_RE:  array<f32, COUNT> = array(...)
 *   const DIRAC_SPARSE_IM:  array<f32, COUNT> = array(...)
 *
 * COUNT = (latticeDim + 1) * S.
 *
 * If latticeDim is outside the sparse range, emits an empty block so the
 * kernel's compile-time dispatch selects the dense path.
 *
 * @param latticeDim - Spatial lattice dimension.
 * @returns WGSL block with const tables and a USE_SPARSE flag, or a single
 *          flag-only block when sparse is disabled for this dim.
 */
export function generateDiracSparseGammaBlock(latticeDim: number): string {
  if (latticeDim < 1 || latticeDim > DIRAC_SPARSE_MAX_DIM) {
    return `
// Dirac sparse gamma disabled for latticeDim=${latticeDim} (uses dense path).
const DIRAC_USE_SPARSE_GAMMA: bool = false;
// Stub tables so references compile (never read — USE_SPARSE_GAMMA is false).
const DIRAC_SPARSE_COUNT: u32 = 1u;
const DIRAC_SPARSE_S: u32 = 1u;
const DIRAC_SPARSE_COL: array<u32, 1> = array<u32, 1>(0u);
const DIRAC_SPARSE_RE: array<f32, 1> = array<f32, 1>(0.0);
const DIRAC_SPARSE_IM: array<f32, 1> = array<f32, 1>(0.0);
`
  }

  const tables = buildDiracSparseTables(latticeDim)
  const s = tables[0]!.rows.length
  const count = tables.length * s

  const cols: number[] = []
  const res: number[] = []
  const ims: number[] = []
  for (const m of tables) {
    for (const cell of m.rows) {
      cols.push(cell.col)
      res.push(cell.re)
      ims.push(cell.im)
    }
  }

  const colLit = cols.map((c) => `${c}u`).join(', ')
  const reLit = res.map(wgslF32).join(', ')
  const imLit = ims.map(wgslF32).join(', ')

  return `
// Dirac sparse gamma tables for latticeDim=${latticeDim}, S=${s}.
// Layout: matIdx * S + row. Alpha matrices 0..${latticeDim - 1}, beta at index ${latticeDim}.
// Every row has exactly one non-zero complex entry (monomial matrices);
// sparse read produces IEEE bit-identical output to dense S-wide multiply.
const DIRAC_USE_SPARSE_GAMMA: bool = true;
const DIRAC_SPARSE_COUNT: u32 = ${count}u;
const DIRAC_SPARSE_S: u32 = ${s}u;
const DIRAC_SPARSE_COL: array<u32, ${count}> = array<u32, ${count}>(${colLit});
const DIRAC_SPARSE_RE: array<f32, ${count}> = array<f32, ${count}>(${reLit});
const DIRAC_SPARSE_IM: array<f32, ${count}> = array<f32, ${count}>(${imLit});
`
}
