/**
 * Sparse monomial gamma-table tests.
 *
 * Dirac α-matrices and β generated by the Pauli-tensor-product + standard-form
 * permutation are monomial (1 non-zero complex entry per row). The sparse
 * specialization emitted into the kinetic and write-grid kernels relies on
 * this invariant — if it ever breaks, the sparse path silently emits wrong
 * output.
 *
 * These tests verify:
 *   1. Every dimension 1..11 produces monomial matrices (sanity check on the
 *      generator that the sparse emitter consumes).
 *   2. For the dimensions covered by the sparse specialization (1..4), the
 *      emitted (col, re, im) tuples, when re-expanded to dense form, equal
 *      `generateDiracMatricesFallback` exactly — so the sparse path is
 *      IEEE bit-identical to the dense path at runtime.
 *   3. The emitted WGSL block wires the USE_SPARSE flag correctly.
 */

import { describe, expect, it } from 'vitest'

import {
  generateDiracMatricesFallback,
  spinorSize,
} from '@/lib/physics/dirac/cliffordAlgebraFallback'
import {
  composeDiracInitShader,
  composeDiracInitShader3D,
} from '@/rendering/webgpu/passes/DiracComputePassSetup'
import {
  buildDiracSparseTables,
  DIRAC_SPARSE_INIT_MAX_DIM,
  DIRAC_SPARSE_MAX_DIM,
  generateDiracSparseGammaBlock,
} from '@/rendering/webgpu/shaders/schroedinger/compute/diracSparseGammaVariants.wgsl'

describe('Dirac sparse gamma tables', () => {
  it('every matrix has exactly one non-zero per row for dims 1..11', () => {
    for (let dim = 1; dim <= 11; dim++) {
      const s = spinorSize(dim)
      const { gammaData } = generateDiracMatricesFallback(dim)
      const matSize = s * s * 2
      for (let m = 0; m < dim + 1; m++) {
        const offset = 1 + m * matSize
        for (let r = 0; r < s; r++) {
          let nnz = 0
          for (let c = 0; c < s; c++) {
            const re = gammaData[offset + (r * s + c) * 2]!
            const im = gammaData[offset + (r * s + c) * 2 + 1]!
            if (re !== 0 || im !== 0) nnz++
          }
          expect(nnz).toBe(1)
        }
      }
    }
  })

  it('sparse tables reconstruct the dense matrices bit-exactly for dims 1..4', () => {
    for (let dim = 1; dim <= DIRAC_SPARSE_MAX_DIM; dim++) {
      const s = spinorSize(dim)
      const { gammaData } = generateDiracMatricesFallback(dim)
      const matSize = s * s * 2
      const tables = buildDiracSparseTables(dim)
      expect(tables).toHaveLength(dim + 1)

      for (let m = 0; m < dim + 1; m++) {
        const offset = 1 + m * matSize
        const sparse = tables[m]!
        expect(sparse.rows).toHaveLength(s)

        for (let r = 0; r < s; r++) {
          const cell = sparse.rows[r]!
          // The sparse cell must match the dense entry at (r, cell.col) bit-exactly.
          const denseRe = gammaData[offset + (r * s + cell.col) * 2]!
          const denseIm = gammaData[offset + (r * s + cell.col) * 2 + 1]!
          expect(cell.re).toBe(denseRe)
          expect(cell.im).toBe(denseIm)
          expect(cell.re === 0 && cell.im === 0).toBe(false)

          // Every OTHER column on this row must be exactly zero.
          // `±0` both satisfy IEEE bit-identity for the dense vs sparse sum:
          // dense starts acc = 0 and adds terms `(±0)·psi = ±0`; any path
          // through the sum ends at the single non-zero term's exact value.
          // The generator emits −0 for entries like −σ₂[0,0] before permutation
          // (e.g., σ₂ carries imag(-1) in (0,1)). Allow both signed zeros.
          for (let c = 0; c < s; c++) {
            if (c === cell.col) continue
            const reAbs = Math.abs(gammaData[offset + (r * s + c) * 2]!)
            const imAbs = Math.abs(gammaData[offset + (r * s + c) * 2 + 1]!)
            expect(reAbs).toBe(0)
            expect(imAbs).toBe(0)
          }
        }
      }
    }
  })

  it('emitted WGSL block enables sparse path inside specialization range', () => {
    for (let dim = 1; dim <= DIRAC_SPARSE_MAX_DIM; dim++) {
      const block = generateDiracSparseGammaBlock(dim)
      expect(block).toContain('DIRAC_USE_SPARSE_GAMMA: bool = true')
      const s = spinorSize(dim)
      expect(block).toContain(`DIRAC_SPARSE_S: u32 = ${s}u`)
      expect(block).toContain(`DIRAC_SPARSE_COUNT: u32 = ${(dim + 1) * s}u`)
    }
  })

  it('emitted WGSL block disables sparse path outside specialization range', () => {
    for (const dim of [5, 7, 11]) {
      const block = generateDiracSparseGammaBlock(dim)
      expect(block).toContain('DIRAC_USE_SPARSE_GAMMA: bool = false')
      // Stub tables are still emitted so the kernel's reads (in the sparse
      // branch, which is dead for this dim) resolve at WGSL compile time.
      expect(block).toContain('DIRAC_SPARSE_COL')
      expect(block).toContain('DIRAC_SPARSE_RE')
      expect(block).toContain('DIRAC_SPARSE_IM')
    }
  })

  it('rejects out-of-range dims with a disabled block rather than throwing', () => {
    expect(() => generateDiracSparseGammaBlock(0)).not.toThrow()
    expect(() => generateDiracSparseGammaBlock(12)).not.toThrow()
    expect(generateDiracSparseGammaBlock(0)).toContain('DIRAC_USE_SPARSE_GAMMA: bool = false')
    expect(generateDiracSparseGammaBlock(12)).toContain('DIRAC_USE_SPARSE_GAMMA: bool = false')
  })

  it('can emit init-projector tables for every supported Dirac dimension', () => {
    for (let dim = 1; dim <= DIRAC_SPARSE_INIT_MAX_DIM; dim++) {
      const block = generateDiracSparseGammaBlock(dim, DIRAC_SPARSE_INIT_MAX_DIM)
      expect(block).toContain('DIRAC_USE_SPARSE_GAMMA: bool = true')
      expect(block).toContain(`DIRAC_SPARSE_S: u32 = ${spinorSize(dim)}u`)
    }
  })

  it('Dirac init shader applies energy projectors instead of upper/lower basis split', () => {
    for (const shader of [composeDiracInitShader(5), composeDiracInitShader3D(3)]) {
      expect(shader).toContain('initProjectorNorm')
      expect(shader).toContain('posBaseRe[0] = cosHalf')
      expect(shader).toContain('negBaseRe[halfS] = cosHalf')
      expect(shader).toContain('projectedRe')
      expect(shader).toContain('DIRAC_USE_SPARSE_GAMMA: bool = true')
    }
  })
})
